server:
  port: 7000
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: utf-8
spring:
  application:
    name: func-web-simple
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
func-link:
    # 默认代理模式
    singleton: true
    # 默认开启lambda模式
    lambda: true
    # 默认的callback回调函数类
    call-back: org.func.spring.boot.component.callback.SimpleFuncCallback
    # logger 配置
    logger:
      # 默认false 不输出日志
      enable-log: false
      # 默认输出日志信息
      message: "call method --> ${methodName}(${parameterSource})"
      # 日志执行日志格式化
      date-format: "yyyy-MM-dd HH:mm:ss"
      # 输出日志的文件名
      file-name: "simple"